### ISSUE TITLE
Issues with MaxPermSize

### ISSUE THREAD

**Issue by ChloeDawn** [hedgehog1029/Launcher#8]
I have it set to 0 yet it is defaulting to 128M

![Screenshot of test launcher options dialog](https://i.imgur.com/XLoO2ei.png)

However, this option should be removed entirely as it has not been supported since Java 8.

`OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0`

https://github.com/hedgehog1029/Launcher/blob/ee272cbbc13767690fccc8ceb78db421e860d6c8/launcher/src/main/java/com/skcraft/launcher/launch/JavaProcessBuilder.java#L106

**Comment by hedgehog1029** [comment]
it's only a warning, and since it's unsupported it won't affect anything anyway. we still technically support down to Java 6, though I think modern versions of the game require 8.

also - I should probably disable issues on this repo again as I'm now exclusively working on the upstream project ([SKCraft/Launcher](https://github.com/SKCraft/Launcher)).
